#!/usr/bin/env python
# -*- coding: utf-8 -*-

import getopt
import sys

sys.path.append('../modules/')
import csocketo
import cmsgo

#+++++++++++++++++++------________________________
#** D E B U G
#** 1 - ON / 0 - OFF
#-------------------------------------------------
DEBUG_MESSAGE = 0
DEBUG_NO_CARD = 0
#-------------------------------------------------


#+++++++++++++++++++------________________________
#** M A I N
#************************************************    
def main():
    # parse command line options
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.error, msg:
        print msg
        print "for help use --help"
        sys.exit(2)
    # process options
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            sys.exit(0)
    # process arguments
    for arg in args:
        process(arg) # process() is defined elsewhere
        
    app = csocketo.App()
    enc_sec_msg = app.Receive_Enc_Aut_Msg(DEBUG_MESSAGE)
    dec_sec_msg = cmsgo.Decrypt_Sec_Msg(enc_sec_msg, DEBUG_MESSAGE, DEBUG_NO_CARD)
    app.Send_Encrypted_Msg_To_Server(dec_sec_msg, DEBUG_MESSAGE, DEBUG_NO_CARD)


if __name__ == "__main__":
    main()

