#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
GnuPGPythonTunnel - Secure network communication based on OpenPGP 
                   smart-card authentication

Copyright (C) 2011  Vaclav Bobek

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import getopt
import sys
sys.path.append('../modules/')
import csocketo
import cmsgo

#+++++++++++++++++++------________________________
#** D E B U G
#** 1 - ON / 0 - OFF
#-------------------------------------------------
DEBUG_MESSAGE = 0
DEBUG_NO_CARD = 0
#-------------------------------------------------

#+++++++++++++++++++------________________________
#** M A I N
#************************************************    
def main():
    # parse command line options
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.error, msg:
        print msg
        print "for help use --help"
        sys.exit(2)
    # process options
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            sys.exit(0)
    # process arguments
    for arg in args:
        process(arg) # process() is defined elsewhere
        
    app = csocketo.App()
    enc_sec_msg = app.Receive_Enc_Aut_Msg(DEBUG_MESSAGE)
    dec_sec_msg = cmsgo.Decrypt_Sec_Msg(enc_sec_msg, DEBUG_MESSAGE, DEBUG_NO_CARD)
    app.Send_Encrypted_Msg_To_Server(dec_sec_msg, DEBUG_MESSAGE, DEBUG_NO_CARD)


if __name__ == "__main__":
    main()

